/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from src/ts/goog-adapters.ts:
/** @const */
var goog_adapters = {};
/** @type {?} */
var app;
// externs from src/ts/react-version.ts:
/** @const */
var react_version = {};
/** @type {{version: string}} */
var React;
// externs from src/ts/react.d.ts:
/** @type {?} */
var React;
/** @type {{render: ?}} */
var ReactDOM;
