/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from src/ts/closure-modules.d.ts:
/** @const */
var ಠ_ಠ = {};
/** @const */
ಠ_ಠ.clutz = {};
/** @const */
ಠ_ಠ.clutz.app = {};
// Derived from: declare module "goog:app"
/** @const */
var goog_app = {};
goog_app.app = ಠ_ಠ.clutz.app;
/** @const */
ಠ_ಠ.clutz.app.lib = {};

/**
 * @param {number} a
 * @param {number} b
 * @return {number}
 */
ಠ_ಠ.clutz.app.lib.sum = function(a, b) {};
// Derived from: declare module "goog:app.lib"
/** @const */
var goog_app$lib = {};
goog_app$lib.lib = ಠ_ಠ.clutz.app.lib;
/** @const */
ಠ_ಠ.clutz.other = {};

/**
 * @param {string} uri
 * @return {string}
 */
ಠ_ಠ.clutz.other.getUriPath = function(uri) {};
// Derived from: declare module "goog:other"
/** @const */
var goog_other = {};
goog_other.other = ಠ_ಠ.clutz.other;
// externs from src/ts/react.d.ts:
/** @type {?} */
var React;
/** @type {{render: ?}} */
var ReactDOM;
